---
hydra:
    run:
        dir: "${general.log_path}/\
            ${now:%Y-%m-%d}-${now:%H-%M-%S}-${general.exp_name}"
    sweep:
        dir: "${general.log_path}/\
            ${now:%Y-%m-%d}-${now:%H-%M-%S}-${general.exp_name}-multirun"

defaults:
    - datasets: ???
    - dataloaders: ???
    - _self_

# General Parameters
general:
    exp_name: ???
    run_mode: ???   # train, test
    seed: ???
    log_path: ???

# Logging Parameters
logging:
    log_level:
        file: 10    # debug
        stream: 10
