---
feat_dim: 256

c2ltregressor1:
  _target_: c2l.models.loftr.c2ltregressor1.C2LTRegressor1
  img_backbone:
    _target_: c2l.models.loftr.resnet_fpn.ResNetFPN
    input_dim: 3
    initial_dim: 128
    block_dims:
      - 128
      - 196
      - ${....feat_dim}
    num_down: 2
    num_up: 2
  pcl_backbone:
    _target_: c2l.models.loftr.simple_pcl_encoder.SimplePCLEncoder
    in_channels: 4
    out_channels: ${...feat_dim}
    kernel_size: 1
  pos_encoding:
    _target_: c2l.models.loftr.pos_encodings.PositionEncodingSine
    dim: ${...feat_dim}
  loftr_coarse:
    _target_: c2l.models.loftr.loftr.LocalFeatureTransformer
    dim: ${...feat_dim}
    nhead: 8
    nlayers: 6
  transf_decoder:
    _target_: c2l.models.loftr.transf_decoder.TransformationDecoder
    dim: ${...feat_dim}
    nhead: 8
    nlayers: 3
    heads:
      trans:
        _target_: torch.nn.Linear
        in_features: ${.....feat_dim}
        out_features: 6
      rot:
        _target_: torch.nn.Linear
        in_features: ${.....feat_dim}
        out_features: 5
