---
feat_dim: 256

loftr:
  _target_: c2l.models.loftr.loftr_model.LoFTR
  img_backbone:
    _target_: c2l.models.loftr.resnet_fpn.ResNetFPN
    input_dim: 3
    initial_dim: 128
    block_dims:
      - 128
      - 196
      - ${...feat_dim}
    num_down: 2
    num_up: 2
  pcl_backbone:
    _target_: torch.nn.Conv2D
    in_channels: 4
    out_channels: ${...feat_dim}
    kernel_size: 1
  pos_encoding:
    _target_: c2l.models.loftr.pos_encodings.PositionEncodingSine
    dim: ${...feat_dim}
  loftr_coarse:
    dim: ${...feat_dim}
    nhead: 8
    nlayers: 6
